name: flutter_create_coach_5x1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_tts: ^4.2.3
  video_player: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/geral/
    - assets/levantador/
    - assets/ponteiro1/
    - assets/ponteiro2/
    - assets/central1/
    - assets/central2/
    - assets/oposto/
    - assets/quadra/
    - assets/libero/
    - assets/6x0/
    - assets/4x2/
    - assets/4x2i/
    - assets/5x1/
    - assets/videos/levantador5x1.mp4
    - assets/videos/oposto5x1.mp4
    - assets/videos/libero5x1.mp4
    - assets/videos/central15x1.mp4
    - assets/videos/central25x1.mp4
    - assets/videos/ponteiro15x1.mp4
    - assets/videos/ponteiro25x1.mp4

# 👇 ESTA PARTE FICA FORA DA SEÇÃO "flutter:"
flutter_native_splash:
  color: "#ffffff"
  image: assets/geral/Logo_Redondo_Sem_Misto.png
  android: true
  ios: true
  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/geral/Logo_Redondo_Sem_Misto.png"
